CREATE DATABASE idgs803_escuela;
USE idgs803_escuela;

DROP TABLE IF EXISTS alumnos;

CREATE TABLE alumnos(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
nombre VARCHAR(50),
apellidos VARCHAR(50),
grupo VARCHAR(50),
email VARCHAR(100)
);

DROP TABLE IF EXISTS maestros;

CREATE TABLE maestros(
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
nombre VARCHAR(50),
apellidos VARCHAR(50),
materia VARCHAR(100),
email VARCHAR(100)
);